version: '3.8'

services:

  mongo:
    image: mongo:6.0.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: checkout
    networks:
      - mongo_net

networks:
  mongo_net:
