version: '3.8'

services:

  mongo:
    image: mongo:6.0.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: checkout
    networks:
      - mongo_net
  mock-bank:
    image: cko-mock-bank
    build:
      context: .
      dockerfile: MockBankDockerfile
    ports:
      - 5251:80

networks:
  mongo_net:
